language: python
python:
  - "3.8"

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - export DB_HOST=${DB_HOST}
  - export DB_NAME=${DB_NAME}
  - export DB_USER=${DB_USER}
  - export DB_PASSWORD=${DB_PASSWORD}

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"